Repository beyond-sw-camp/be08-fin-EasyCheck-EasyStay-front-admin, pull requests merged in 2024-10, with the labels that each got.

#4 [Fix/#3/version] 라이브러리 버전 롤백
  package.json
Labels: bug

#8 [Design/#5/AdminMain] 메인페이지 헤더, 사이드바, 로고 관련 구현
  src/assets/img/002.png
  src/assets/img/logo-ct-dark.png
  src/assets/scss/argon-dashboard/_navbar-vertical.scss
  src/assets/scss/argon-dashboard/_variables.scss
  src/assets/scss/argon-dashboard/custom/_styles.scss
  src/examples/Breadcrumbs.vue
  src/examples/Charts/GradientLineChart.vue
  src/examples/Footer.vue
  src/examples/Navbars/Navbar.vue
  src/examples/PageLayout/Footer.vue
  src/examples/PageLayout/Navbar.vue
  src/examples/Sidenav/SidenavCard.vue
  src/examples/Sidenav/SidenavList.vue
  src/examples/Sidenav/index.vue
  src/router/index.js
  src/views/AdditionalServiceList.vue
  src/views/AmenitiesList.vue
  src/views/Dashboard.vue
  src/views/DiningList.vue
  src/views/EventList.vue
  src/views/NoticeRegistration.vue
  src/views/NoticesList.vue
  src/views/Rtl.vue
  src/views/SuggestionList.vue
  src/views/ThemeParksList.vue
  src/views/ThemeParksRegistration.vue
Labels: Design, Frontend

#10 [Design/#9/notices registration] 공지사항 등록 페이지 구현
  src/assets/js/nav-pills.js
  src/examples/Charts/GradientLineChart.vue
  src/views/Dashboard.vue
  src/views/NoticeRegistration.vue
Labels: Design, Frontend

#12 [design/#11/EventRegistration] 이벤트 등록 페이지 구현
  src/views/Profile.vue
  src/views/components/ProfileCard.vue
Labels: Design, Frontend

#14 [design/#13/ThemeParksRegistration] 테마파크 등록 페이지 구현
  src/views/NoticeRegistration.vue
  src/views/Profile.vue
  src/views/ThemeParksRegistration.vue
  src/views/components/ProfileCard.vue
Labels: Design, Frontend

#17 design : 공지사항 리스트 페이지 구현
  src/views/NoticesList.vue
  src/views/ThemeParksList.vue
  src/views/components/NoticesTable.vue
  src/views/components/ThemeParksTable.vue
Labels: Design, Frontend

#18 design : 이벤트 목록 페이지 구현
  src/views/EventList.vue
  src/views/components/EventTable.vue
Labels: Design, Frontend

#21 design : 편의시설 목록 페이지 구현
  src/views/AmenitiesList.vue
  src/views/components/AmenitiesTable.vue
Labels: Design, Frontend

#23 design : 목록 페이지 끝
  src/assets/img/004.png
  src/assets/img/005.png
  src/assets/img/006.png
  src/assets/img/007.png
  src/assets/img/008.png
  src/assets/img/009.png
  src/assets/img/010.png
  src/views/AdditionalServiceList.vue
  src/views/AmenitiesList.vue
  src/views/DiningList.vue
  src/views/EventList.vue
  src/views/SuggestionList.vue
  src/views/ThemeParksList.vue
  src/views/components/ResponseForm.vue
  src/views/components/SuggestionTable.vue
Labels: Design, Frontend

#25 design : 결제 고객 목록 페이지 구현
  src/assets/img/012.png
  src/views/Tables.vue
  src/views/components/PaymentTable.vue
Labels: Design, Frontend

#26 design : 로그인/로그아웃 페이지 구현
  src/assets/img/013.png
  src/examples/Navbars/Navbar.vue
  src/router/index.js
  src/views/Signin.vue
  src/views/Signup.vue
Labels: Design, Frontend

#28 [chore/#27/axios]: axios 설정
  src/api/index.js
Labels: Chore, Frontend

#30 [Chore/#29/vuex] vuex 스토어 모듈화
  src/App.vue
  src/examples/Sidenav/index.vue
  src/store/index.js
  src/store/modules/layout.js
  src/views/Signin.vue
  src/views/Signup.vue
Labels: Chore, Frontend

#33 feat : 공지사항 등록 기능 구현
  src/api/index.js
  src/store/index.js
  src/store/modules/notice.js
  src/views/NoticeRegistration.vue
  src/views/NoticesList.vue
  src/views/components/NoticesTable.vue
Labels: Feat, Frontend

#37 feat : 부대시설 목록 조회 연동 및 사이드바 수정
  src/examples/Sidenav/SidenavList.vue
  src/store/index.js
  src/store/modules/dining.js
  src/views/DiningList.vue
  src/views/components/DiningTable.vue
Labels: Feat, Frontend

#39 feat : 부가서비스 목록 전체 조회 기능 연동
  src/api/index.js
  src/store/index.js
  src/store/modules/service.js
  src/views/AdditionalServiceList.vue
Labels: Feat, Frontend

#42 design : 테마파크 시설 더보기 버튼 시 시설 목록 전체 조회
  src/views/components/ThemeParksTable.vue
Labels: Design, Frontend

#44 feat : 건의사항 목록 전체 조회 기능 연동
  src/store/index.js
  src/store/modules/suggestion.js
  src/views/SuggestionList.vue
  src/views/components/SuggestionTable.vue
Labels: Feat, Frontend

#45 feat : 건의사항 목록 전체 조회 및 답변 전송 기능 연동
  src/store/modules/suggestion.js
  src/views/SuggestionList.vue
  src/views/components/ResponseForm.vue
  src/views/components/SuggestionTable.vue
Labels: Feat, Frontend

#47 design : 매출 현황 페이지 구현
  package.json
  src/examples/Charts/MoneyGraphChart.vue
  src/examples/Charts/PieChart.vue
  src/examples/Charts/PieChartRoom.vue
  src/examples/Charts/PieChartService.vue
  src/examples/Charts/PieChartTheme.vue
  src/examples/Sidenav/SidenavList.vue
  src/router/index.js
  src/views/MoneyGraph.vue
  src/views/components/Carousel.vue
Labels: Design, Frontend

#54 feat : 이벤트 등록 페이지 기능 연동
  src/store/modules/event.js
  src/views/Profile.vue
Labels: Feat, Frontend

#55 feat : 이벤트 삭제 버튼 기능 연동
  src/store/modules/event.js
  src/views/components/EventTable.vue
Labels: Feat, Frontend

#58 feat : 결제 고객 목록 페이지 기능 연동
  src/store/modules/pay.js
  src/views/SuggestionList.vue
  src/views/Tables.vue
  src/views/components/PaymentTable.vue
Labels: Design, Feat, Frontend

#60 design: 매출 현황 페이지 막대그래프로 수정
  src/examples/Charts/PieChart.vue
  src/examples/Charts/PieChartRoom.vue
  src/examples/Charts/PieChartService.vue
  src/examples/Charts/PieChartTheme.vue
Labels: Design, Frontend

#62 feat : 공지사항 수정 페이지 기능 연동
  src/router/index.js
  src/store/modules/notice.js
  src/views/NoticesList.vue
  src/views/components/NoticeEdit.vue
  src/views/components/NoticesTable.vue
Labels: Feat, Frontend

#64 design : 건의사항 목록 내용 추가
  src/store/modules/suggestion.js
  src/views/components/SuggestionTable.vue
Labels: Design, Frontend

#66 design: 이벤트 등록 페이지 디자인 수정
  src/router/index.js
  src/store/modules/event.js
  src/views/Profile.vue
  src/views/components/EventEdit.vue
  src/views/components/EventTable.vue
  src/views/components/SuggestionTable.vue
Labels: Design, Frontend

#67 refactor : 로그인 크기 재수정 및 메인페이지 리조트 이름 추가
  src/examples/Navbars/Navbar.vue
  src/views/Signin.vue
  src/views/components/EventEdit.vue
Labels: Frontend, Refactor

#68 [Feat/#65/event update] 결제자 마스킹 처리 및 사이드바에서 부대시설, 부가서비스 제거
  src/examples/Navbars/Navbar.vue
  src/examples/Sidenav/SidenavList.vue
  src/views/components/PaymentTable.vue
Labels: Design, Frontend

#70 design: 결제자 이메일 추가 및 결제 일자 추가
  src/store/modules/pay.js
  src/views/components/PaymentTable.vue
Labels: Design, Frontend

#71 design: 결제고객목록 페이지 페이지네이션처리
  src/views/components/PaymentTable.vue
Labels: Design, Frontend
